booking/urls.py
from django.urls import path
from django.conf.urls import url
from .views.booking_table_view import BookingTableView
from .views.booking_print_view import BookingPrintView
from .views.booking_add_view import BookingAddView
from .views.booking_edit_table_view import BookingEditTableView
from .views.booking_time_table_view import BookingTimeTableView
# from .views.authentication_view import AuthenticationView


urlpatterns = [
    url(r'^$', BookingTableView.get_table, name='booking-table'),
    url(r'^print/(?P<pk>\d+)/(?P<template>\w+)/$', BookingPrintView.as_view(), name='booking-print'),

    url(r'^add/$', BookingAddView.add_booking, name='booking-add'),
    url(r'^save/$', BookingAddView.save_booking, name='booking-save'), 

    url(r'^delete/(?P<pk>\d+)/$', BookingTableView.delete_data, name='booking-delete'), #delete in table page
    url(r'^update/$', BookingTableView.update_data, name='booking-update'), #update in table page

    url(r'^edit/$', BookingEditTableView.get_edit_table, name='booking-edit'),
    url(r'^edit/save/$', BookingEditTableView.save_edit_table, name='booking-edit-save'),

    url(r'^time/$', BookingTimeTableView.time_table, name='booking-time'),
    url(r'^time/save/$', BookingTimeTableView.save_time_table, name='booking-time-save'),
]

ndd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from booking.views.authentication_view import AuthenticationView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('agent-transport/', include('agent_transport.urls')),

    url(r'^login555/$', AuthenticationView.login, name='login'),
    url(r'^logout/$', AuthenticationView.logout, name='logout'),

]

booking/models.py
from django.db import models
from datetime import datetime
from customer.models import Principal, Shipper

# Create your models here.

class Booking(models.Model):
    time = models.CharField(max_length=50, blank=True, default='')
    date = models.DateField(default=datetime.now, null=True)
    principal = models.ForeignKey(Principal, on_delete=models.SET_NULL, null=True, blank=True)
    shipper = models.ForeignKey(Shipper, on_delete=models.SET_NULL, null=True, blank=True)
    agent = models.CharField(max_length=50, blank=True)
    size = models.CharField(max_length=50, blank=True)
    booking_no = models.CharField(max_length=50, blank=True)
    booking_color = models.CharField(max_length=20, blank=True, default='')

    pickup_tr = models.CharField(max_length=20, blank=True, default='')
    pickup_from = models.CharField(max_length=20, blank=True, default='')
    forward_tr = models.CharField(max_length=20, blank=True, default='')
    factory = models.CharField(max_length=20, blank=True, default='')
    backward_tr = models.CharField(max_length=20, blank=True, default='')
    return_tr = models.CharField(max_length=20, blank=True, default='')
    return_to = models.CharField(max_length=20, blank=True, default='')

    container_no = models.CharField(max_length=50, blank=True)
    seal_no = models.CharField(max_length=50, blank=True)
    vessel = models.CharField(max_length=50, blank=True)
    port = models.CharField(max_length=50, blank=True)
    closing_date = models.DateField(max_length=20, null=True, blank=True, default=None)
    closing_time = models.CharField(max_length=20, blank=True)
    ref = models.CharField(max_length=50, blank=True, default='')
    remark = models.CharField(max_length=200, blank=True)
    
    work_id = models.CharField(max_length=50, blank=True)
    work_number = models.IntegerField(default=0)

    pickup_date = models.DateField( blank=True, null=True)
    factory_date = models.DateField(blank=True, null=True)
    return_date = models.DateField(blank=True, null=True)

    pickup_in_time = models.CharField(max_length=20, blank=True, default='')
    pickup_out_time = models.CharField(max_length=20, blank=True, default='')
    factory_in_time = models.CharField(max_length=20, blank=True, default='')
    factory_load_start_time = models.CharField(max_length=20, blank=True, default='')
    factory_load_finish_time = models.CharField(max_length=20, blank=True, default='')
    factory_out_finish = models.CharField(max_length=20, blank=True, default='')
    return_in_time = models.CharField(max_length=20, blank=True, default='')
    return_out_time = models.CharField(max_length=20, blank=True, default='')

    ADDRESS_CHOICES = (
        ('shipper', 'Shipper'),
        ('other', 'Other'),
        ('none', 'None'),
    )
    address = models.CharField(max_length=10, choices=ADDRESS_CHOICES, default='shipper')
    address_other = models.CharField(max_length=500, blank=True, default='')

    CANCEL_CHOICES = (
        ('1', 'Cancel'),
        ('0', '-'),
    )
    cancel = models.CharField(max_length=1, choices=CANCEL_CHOICES, default=0)

    def __str__(self) :
        return self.work_id

booking/views/authentication_view.py
from django.contrib import auth
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView


@csrf_protect
class AuthenticationView(TemplateView):

    def login(request):
        template_name = 'login.html'

        if request.user.is_authenticated:
            return redirect('booking-table')

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                if request.POST['remember_me'] == '1':
                    request.session.set_expiry(604800)
                return redirect('booking-table')

            else:
                messages.error(request, 'Incorrect Username or Password')

        return render(request, template_name)


    
    def logout(request):
        auth.logout(request)
        return redirect('login')

booking/views/booking_add_view.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from ..models import Booking
from customer.models import Principal, Shipper
from ..forms import BookingAddForm
# from django.shortcuts import render_to_response
from datetime import datetime
from django.db.models import Max
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required


class BookingAddView(TemplateView):

    @login_required(login_url=reverse_lazy('login'))
    def add_booking(request):
        add_booking = BookingAddView()
        template_name = 'booking/booking_add.html'
        context = {}
        context['form'] = BookingAddForm()
        context['principals'] = Principal.objects.all().order_by('name')
        context['nbar'] = 'booking-table'
        if request.method == 'POST':
            context = add_booking.create_context(request.POST)
            
        return render(request, template_name, context)

    def create_context(self, req):
        context = {}
        # context['form'] = BookingAddForm()
        context['principals'] = Principal.objects.all().order_by('name')
        if 'principal' in req:
            # print(request.POST)
            context['principal'] = req.get('principal')
            if context['principal']:
                context['shippers'] = Shipper.objects.filter(principal=context['principal']).order_by('name')
            else:
                context['shippers'] = []

            req._mutable = True
            context['size'] = req.getlist('size')
            context['quantity'] = req.getlist('quantity')
            context['date'] = req.getlist('date')
            context['zip'] = zip(context['size'], context['quantity'], context['date'])

            req.update({'size':'', 'quantity':'', 'date':''})
            context['form'] = BookingAddForm(req)
        return context

    @login_required(login_url=reverse_lazy('login'))
    def save_booking(request):
        add_booking = BookingAddView()
        if request.method == 'POST':
            form = BookingAddForm(request.POST)
            if form.is_valid():
                # print(request.POST)
                principal = request.POST['principal']
                shipper = request.POST['shipper']
                agent = request.POST['agent']
                booking_no = request.POST['booking_no']
                booking_color = request.POST['booking_color']
                size = request.POST.getlist('size')
                quantity = request.POST.getlist('quantity')
                date = request.POST.getlist('date')
                pickup_from = request.POST['pickup_from']
                factory = request.POST['factory']
                return_to = request.POST['return_to']
                vessel = request.POST['vessel']
                port = request.POST['port']
                closing_date = request.POST['closing_date']
                closing_time = request.POST['closing_time']
                ref = request.POST['ref']
                remark = request.POST['remark']
                address = request.POST['address']

                cut = request.POST['cut']

                if not closing_date:
                    closing_date = None
                if address == 'other':
                    address_other = request.POST['address_other']

                container = zip(size, quantity, date)
                for s, q, d in container:
                    add_booking.work_id_after_add(d, shipper, int(q))
                    
                    if cut == '1':
                        return_date = request.POST['return_date']
                    else:
                        return_date = d

                    for i in range(int(q)):
                        work_id, work_number = add_booking.run_work_id(d, shipper)
                        data = {
                            'principal': Principal.objects.get(pk=principal),
                            'shipper': Shipper.objects.get(pk=shipper),
                            'agent': agent,
                            'booking_no': booking_no,
                            'booking_color': booking_color,
                            'size': s,
                            'date': d,
                            'pickup_from': pickup_from,
                            'factory': factory,
                            'return_to': return_to,
                            'vessel': vessel,
                            'port': port,
                            'closing_date': closing_date,
                            'closing_time': closing_time,
                            'ref': ref,
                            'remark': remark,
                            'work_id': work_id,
                            'work_number': work_number,
                            'pickup_date': d,
                            'factory_date': d,
                            'return_date': return_date,
                            'address': address
                        }
                        if address == 'other':
                            data['address_other'] = address_other

                        booking = Booking(**data)
                        booking.save()
                 
                messages.success(request, "Added Booking.")
                return redirect('booking-table')
            messages.error(request, "Form not validate.")
        return redirect('booking-add')


    def run_work_id(self, date, shipper):
        work = Booking.objects.filter(date=date).aggregate(Max('work_number'))
        if work['work_number__max'] == None:
            work_number = 0
        else:
            work_shipper = Booking.objects.filter(date=date, shipper=shipper).aggregate(Max('work_number'))
            if work_shipper['work_number__max'] == None:
                work_number = work['work_number__max'] + 1
            else:
                work_number = work_shipper['work_number__max'] + 1

        work = str("{:03d}".format(work_number))
        d = datetime.strptime(date, "%Y-%m-%d")
        work_id = d.strftime('%d')+d.strftime('%m')+d.strftime('%y')+work
        return work_id, work_number


    def work_id_after_add(self, date, shipper, quantity):
        max_work = Booking.objects.filter(date=date, shipper=shipper).aggregate(Max('work_number'))
        if max_work['work_number__max']:
            work_gt = Booking.objects.filter(date=date, work_number__gt=max_work['work_number__max'])
            for work in work_gt:               
                new_work_number = work.work_number + quantity
                work_str = str("{:03d}".format(new_work_number))
                d = datetime.strptime(date, "%Y-%m-%d")
                work_id = d.strftime('%d')+d.strftime('%m')+d.strftime('%y')+work_str

                booking = Booking.objects.get(pk=work.pk)
                booking.work_id = work_id
                booking.work_number = new_work_number
                booking.save()
        return None

            

booking/views/booking_edit_table_view.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from ..models import Booking
from customer.models import Principal, Shipper
from ..forms import BookingFilterSortForm
# from django.shortcuts import render_to_response
from datetime import datetime, timedelta
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required

class BookingEditTableView(TemplateView):
    
    @login_required(login_url=reverse_lazy('login'))
    def get_edit_table(request):
        template_name = 'booking/booking_edit_table.html'

        tmr = datetime.now() + timedelta(days=1)
        today = datetime.now()

        if request.method == "GET":
            form = BookingFilterSortForm(request.GET)
            date = request.GET.get("date")

            if date == None:
                date = ''

            if not date:
                bookings = Booking.objects.filter(Q(date__month=today.month) | (Q(return_tr='') & ~Q(cancel='1'))).order_by('date', 'work_id')
            else:
                bookings = Booking.objects.filter(Q(date=date) | ((Q(closing_date__lte=tmr) | Q(date__lte=today)) & (Q(return_tr='') & ~Q(cancel='1')))).order_by('date', 'work_id')
        else:
            bookings = Booking.objects.filter(date__month=today.month | (Q(return_tr='') & ~Q(cancel='1'))).order_by('date', 'work_id')

        return render(request, template_name, {'bookings': bookings, 'form': form, 'date': date, 'today': today, 'tmr': tmr, 'nbar': 'booking-table'})

    @login_required(login_url=reverse_lazy('login'))
    def save_edit_table(request):
        if request.method == 'POST':
            pk = request.POST['pk']
            time = request.POST['time']
            date = request.POST['date']
            pickup_tr = request.POST['pickup_tr']
            pickup_from = request.POST['pickup_from']
            forward_tr = request.POST['forward_tr']
            factory = request.POST['factory']
            backward_tr = request.POST['backward_tr']
            return_tr = request.POST['return_tr']
            return_to = request.POST['return_to']
            container_no = request.POST['container_no']
            seal_no = request.POST['seal_no']
            closing_date = request.POST['closing_date']
            closing_time = request.POST['closing_time']
            ref = request.POST['ref']
            remark = request.POST['remark']
            return_date = request.POST['return_date']

            date_filter = request.POST['date_filter']

            if not date:
                date = None
            if not closing_date:
                closing_date = None
            if not return_date:
                return_date = None

            booking = Booking.objects.get(pk=pk)
            booking.time = time
            booking.date = date
            booking.pickup_tr = pickup_tr
            booking.pickup_from = pickup_from
            booking.forward_tr = forward_tr
            booking.factory = factory
            booking.backward_tr = backward_tr
            booking.return_tr = return_tr
            booking.return_to = return_to
            booking.container_no = container_no
            booking.seal_no = seal_no
            booking.closing_date = closing_date
            booking.closing_time = closing_time
            booking.ref = ref
            booking.remark = remark
            booking.pickup_date = date
            booking.factory_date = date
            booking.return_date = return_date
            booking.save()

            messages.success(request, "Saving Booking.")
            return redirect(reverse('booking-edit') + '?date=' + date_filter)
        else:
            return redirect('booking-edit')

templates/booking/booking_add.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block title %} Add Booking {% endblock %}
        
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/style_add_booking.css' %}" />
    <script src="{% static 'js/add-form.js' %}"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove(); 
            });
        }, 2000);
        
        $(function() {
            $(document).on('click', '.add-more', function(e) {
                e.preventDefault();

                var controlForm = $('.control:first'),
                currentEntry = $(this).parents('.entry:first'),
                newEntry = $(currentEntry.clone()).appendTo(controlForm);

                newEntry.find('input').val('');
                controlForm.find('.entry:not(:last) .add-more')
                .removeClass('add-more').addClass('remove')
                .removeClass('btn-success').addClass('btn-danger')
                .html('<span><i class="fa fa-minus"></i></span>');
            }).on('click', '.remove', function(e) {
                $(this).parents('.entry:first').remove();

                e.preventDefault();
                return false;
            });
        });

    </script>
{% endblock %}

{% block content %}
    {% for message in messages %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    <div class="container col-sm-6 shadow bg-white">
        <div class="container col-sm-9">
            <div class="container text-center pt-4 pb-2">
            <h2>Add Booking</h2>
            <hr>
            </div>
            <form method="POST" class="add-form">
                {% csrf_token %}
                        <!-- <form id="customer" method="POST"> -->
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">CUSTOMER</span>
                                    </div>
                                    <select id="id_principal" name="principal" class="custom-select" onchange="this.form.submit();" required>
                                        <option value=""> -------- </option>
                                        {% for p in principals %}
                                            {% ifequal p.pk|stringformat:"s" principal %}
                                                <option value="{{ p.pk }}" selected> {{ p.name }} </option>
                                            {% else %}
                                                <option value="{{ p.pk }}"> {{ p.name }} </option>
                                            {% endifequal %}
                                        {% endfor %}
                                    </select>
                            </div>
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">SHIPPER</span>
                                    </div>
                                <select id="id_shipper" name="shipper" class="custom-select" required>
                                    <option value=""> -------- </option>
                                    {% for s in shippers %}
                                        <option value="{{ s.pk }}"> {{ s.name }} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        <!-- </form> -->
                        <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">AGENT</span>
                                </div>
                            {{ form.agent }} 
                        </div>
                    
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">BOOKING NO.</span>
                            </div>
                            {{ form.booking_no }}
                            {{ form.booking_color }}
                        </div>
                        
                        <fieldset>
                                <legend>CONTAINER</legend>
                        {% if size or quantity or date %}
                            <div class="control">
                                    {% for s, q, d in zip %}
                                    <div class="entry input-group control-group after-add-more mb-2">
                                        <input name="size" class="form-control" id="id_size" placeholder="SIZE" value="{{ s }}" required>
                                        <input type="number" name="quantity" min="1" class="form-control" id="id_quantity" placeholder="QUANTITY" value="{{ q }}" required>
                                        <input type="date" name="date" class="form-control" id="id_date" placeholder="DATE" value="{{ d }}" required>
                                        <div class="input-group-append">
                                    {% if forloop.last %}
                                        <button class="btn btn-success add-more" type="button"><span><i class="fa fa-plus"></i></span></button>     
                                    {% else %}
                                        <button class="btn btn-danger remove" type="button"><span><i class="fa fa-minus"></i></span></button>
                                    {% endif %}
                                        </div>
                                    </div>
                            {% endfor %}
                        </div>
                        {% else %}
                            <div class="control">
                                <div class="entry input-group control-group after-add-more mb-2">
                                        <input name="size" class="form-control" id="id_size" placeholder="SIZE" required>
                                        <input type="number" name="quantity" min="1" class="form-control" id="id_quantity" placeholder="QUANTITY" required>
                                        <input type="date" name="date" class="form-control" id="id_date" placeholder="DATE" required>
                                    <div class="input-group-append">
                                        <button class="btn btn-success add-more" type="button"><span><i class="fa fa-plus"></i></span></button>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </fieldset>
                            
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">FROM</span>
                        </div>
                        {{ form.pickup_from }}
                        <div class="input-group-append">
                            <span class="input-group-text">FACTORY</span>
                        </div>
                        {{ form.factory }}
                        <div class="input-group-append">
                            <span class="input-group-text">TO</span>
                        </div>
                        {{ form.return_to }}
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">VESSEL</span>
                        </div>
                        {{ form.vessel }} 
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">PORT</span>
                        </div>
                        {{ form.port }} 
                    </div>

                    <fieldset>
                        <legend>ตัดหาง</legend>
                        
                        <div class="container input-group mb-2 col-sm-8">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <div class="custom-control custom-checkbox">
                                        <input type="hidden" name="cut" value=0 />
                                        <input type="checkbox" class="custom-control-input" id="cut" name="cut" value=1 onchange="updateCut();">
                                        <label class="custom-control-label" for="cut"></label>
                                    </div>
                                </div>
                                <span class="input-group-text">RETURN DATE</span>
                            </div>
                                <!-- <input type="date" name="return_date" class="form-control" id="id_return_date" disabled> -->
                                    {{ form.return_date }}
                            </div>
                    </fieldset>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">CLOSING</span>
                        </div>
                        {{ form.closing_date }}
                        {{ form.closing_time }} 
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">REF.</span>
                        </div>
                        {{ form.ref }} 
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">REMARK</span>
                        </div>
                        {{ form.remark }} 
                    </div>


                    <fieldset>
                            <legend>ADDRESS</legend>
                    <div class="custom-control custom-radio mb-3">
                        <input type="radio" class="custom-control-input" id="id_address_1" name="address" onchange="updateradio('');" value="shipper" checked>
                        <label class="custom-control-label" for="id_address_1">Shipper</label>
                    </div>

                    <div class="custom-control custom-radio mb-3">
                        <input type="radio" class="custom-control-input" id="id_address_2" name="address" onchange="updateradio('');" value="other">
                        <label class="custom-control-label" for="id_address_2">Other</label><br />
                        <textarea class="form-control" rows="3" id="id_address_other" name="address_other" disabled></textarea>
                    </div>

                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="id_address_3" name="address" onchange="updateradio('');" value="none">
                        <label class="custom-control-label" for="id_address_3">None</label>
                    </div>
                    </fieldset>
                    <div class="text-right pb-4">
                    <button class="btn btn-light btn-lg mr-sm-1" onclick="window.location='{% url 'booking-table' %}'">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-lg" formaction="{% url 'booking-save' %}">SUBMIT</button>
                </div>
            </form>
            
        </div>
        
        </div>
        {% endblock %}
    
   